dist: focal
language: python
git:
  depth: 1

cache:
  apt: true

python:
  - '3.8'
 
install:
  - nvm install node
  - node --version
  - npm --version
  - nvm --version
  - git clone --depth=1 https://github.com/Nic30/hwtLib
  - pip3 install -r hwtLib/docs/requirements.hwt.txt --upgrade --force-reinstall
  - pip3 install ./hwtLib
  - python setup.py install

script:
   

  - python setup.py test 

# script:
#   - coverage run --source=hwtLib setup.py test

deploy:
  provider: pypi
  user: nic30
  on:
    tags: true
    branch: master

